import type { Metadata } from "next";
import { Geist, Inter } from "next/font/google";
import "./styles/globals.css";

import {Footer, Header} from "@/shared/ui";

const inter = Inter({ subsets: ['latin'] });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}  antialiased`}
      >
      <Header/>
        {children}
      <Footer/>
      </body>
    </html>
  );
}
